print("      *     *                *   ")
print("         *             *         ")
print("*            *             *     ")
print("     *       HHH    *     *      ")
print("           HHHHHHHH        *     ")
print(" *     *  HHHHHHHHHH             ")
print("     *   HHHHHHHHHHHH    *     * ")
print("         *   @ @   *             ")
print("        *     o     *            ")
print("  *       *   0    *         *   ")
print("         LLL * * L               ")
print("         * LLLLLLLL *            ")
print("       *      l   LL  *          ")
print("      *       l    L   *         ")
print("      *       l        *         ")
print("       *              *          ")
print("           *   *   *             ")