print('What do you get when you cross a snowman with a vampire?')
input()
print('Frostbite!')
print()
print('what do dentists call an astronaut\'s cavity?')
input()
print('A black hole!')
print()
input('Knock Knock.')
input()
print('who\'s there?')
input()
print('Interupting cow.')
input()
#end= '' passes a blank parameter, it will add a blank string instead of adding a newline
print('Interrupting cow wh', end='')
print('-MOO!')